rules:
  force-element-nesting: 0
  no-trailing-whitespace: 0
  no-color-literals: 0
  trailing-semicolon: 0
  brace-style: 0
  force-pseudo-nesting: 0
  pseudo-element: 0
  property-sort-order: 0
  no-color-keywords: 0
  no-css-comments: 0
  clean-import-paths: 0
  empty-line-between-blocks: 0
  placeholder-in-extend: 0
  indentation:
  - 1
  - size: 4
  nesting-depth:
    - 2
    -
      max-depth: 3
